version: '3'

services:
  app:
    #Имя создаваемого контейнра
    container_name: node-mongo-app-1

    #Параметры перезапуска контейнера
    restart: always

    #Создаем кастомный образ на основании кастомного Dockerfile
    build: ./app

    #Порты. Подключаем 3000 порт контейнера к 80 порту устройства
    ports:
      - '80:3000'
    #
    external_links:
      - mongo

  mongo:
    #Имя создаваемого контейнра
    container_name: mongo

    #Билдим из образа с DockerHub
    image: mongo

    #Порты. Подключаем 27017 порт контейнера к 27017 порту устройства
    ports:
      - '27017:27017'